/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class', // dark mode controlado por la clase .dark en <html>
  theme: {
    extend: {
      colors: {
        primary: "#002147",
        "on-primary": "#ffffff",
        "primary-container": "#d6e2ff",
        "on-primary-container": "#001a41",
        secondary: "#565e71",
        "on-secondary": "#ffffff",
        "secondary-container": "#dae2f9",
        "on-secondary-container": "#131c2b",
        tertiary: "#ff3700",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#ffd9e2",
        "on-tertiary-container": "#de480d",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        background: "#fbfcff",
        "on-background": "#1a1c1e",
        surface: "#fdfbff",
        "on-surface": "#1a1c1e",
        "surface-variant": "#e1e2ec",
        "on-surface-variant": "#44474e",
        outline: "#74777f",
        "outline-variant": "#c4c6d0",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f7f9ff",
        "surface-container": "#f1f4f9",
        "surface-container-high": "#ebeef4",
        "surface-container-highest": "#e2e2e6",
        "primary-fixed": "#d6e2ff",
        "on-primary-fixed": "#001a41",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}